travis:
  secure:
    BINSTAR_TOKEN: W5z9nft4TWLHYOY6w/qwJRBXIbjQnvvgBb7lZauPooW8U3f8X8BFuLEv3M167zAdOdCftdvGZGrik++LuHQugMvpnLMR0Nzp2RpE17xlhjeyPAJns4FoVZSXBPXdSE7Kl3Rnjno1u2gW+8HrSBLTo75wV/QKD5rRl2kzH+1vVGg1wkJIyqvVrTznj6I/7JhdI6tSywtNbuAMW1G8qZVKQDQeHguws7/C5MRX06+8wNN3qwSMehSNmpHVWgblKa1t9KZOQfMzuD6XoleOylpgrTBqzDmD7ECIsdgm9Z22OmX3fjXssSblW9mEHaL0NbF+we7k7S4XY7HUd+Ot+8fP/iifmYvTazCsKbA/XEzSrDHWzqYAr6BwdisJLDG7CzoTGkLakFJZN8l6T03Toa9napZ3Liq3lQyasj2wizgnG/KACtm4K9K17VThmtuEsBK+XcSdsWYTZphdqcs3a8glbpOArs5FJmeB3IRZ8yOEsi3+luMEngM8GpNhbuVcVwJI/Qv4EThyy6p5wagRt+oJcndnzzA+TIg3+YDeXGnY/jaSyXUAZuI6+vwbiW67pfEDfajI2SphuyC0kCdxBOCnLtz9lTckwxyDsF+mU6ssJrg4hGh0PTnLxYHPskXH0/r6a3lbQhjCWLUVGBoR/J18i6nKhxknTtXYV1CqmTdst8U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
